spring:
  datasource:
    url: jdbc:mysql://localhost:3306
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update   # ⭐ 엔티티 → DB 자동 생성
    properties:
      hibernate:
        format_sql: true
    show-sql: true       # SQL 보이기

server:
  port: 8080